#!/bin/sh
echo "doctrine:build-model"
php symfony doctrine:build-model
echo "doctrine:build-sql"
php symfony doctrine:build-sql
echo "doctrine:insert-sql"
php symfony doctrine:insert-sql
echo "doctrine:data-load"
php symfony doctrine:data-load
echo "clear-cache"
php symfony cc
echo "set rights"
chmod a+w data/database/webschach.db
chmod a+w data/database
