<?php

/**
 * GamesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GamesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GamesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Games');
    }
}